### PR TITLE
update babel + add browserify support

### PR DESCRIPTION
**Pull request by charliewolf**

### CODE REVIEW

**Comment by gajus** [comment]
Browserify is not supported.

**Comment by charliewolf** [comment]
Any particular reason why it shouldn't be?

**Comment by gajus** [comment]
All builds have been removed. Whoever needs a browser build can do it themselves.

**Comment by charliewolf** [comment]
@gajus Correct, but the existing builds don't support browserify and without these changes in package.json browserify will not work with swing, so anyone who uses browserify (which is a lot of people) need to fork swing or use a shim in order to use it.

**Comment by gajus** [comment]
That sounds like an issue of Browserify (if it requires modification of the target package to use it), not Swing.

Finally, v3.0.3 ./dist is ES5. No need to use Babel.

**Comment by charliewolf** [comment]
@gajus Is it a bug that npm requires projects to have a `package.json` in them? It seems to me, and please let me know if I'm wrong here, that this change does nothing except allow people to use browserify and does nothing to harm or change the existing build/workflow. The gulp scripts still work fine.

**Comment by gajus** [comment]
> @gajus Is it a bug that npm requires projects to have a package.json in them?

This project uses NPM. It does not use Browserify.

**Comment by charliewolf** [comment]
I understand that. My point is that, without sacrificing any current
functionality, by simply adding a field to your package.json, you could
allow the 2.5 million people who have downloaded browserify this month
alone use your project. If that is not okay with you, I don't understand
why but I guess we'll have to continue using a fork for the project my
team is working on.
 
On Sat, Mar 12, 2016, at 01:14 PM, Gajus Kuizinas wrote:
>> @gajus[1] Is it a bug that npm requires projects to have a
>> package.json in them?
> This project uses NPM. It does not use Browserify.
> —
> Reply to this email directly or view it on GitHub[2].
>
 

Links:

  1. https://github.com/gajus
  2. https://github.com/gajus/swing/pull/61#issuecomment-195793220

**Comment by gajus** [comment]
I think this is an apt use case for a fork.

**Comment by gajus** [comment]
I encourage you to make it public and share it with others.

**Comment by charliewolf** [comment]
It is, that's this PR. I'll need to add it to NPM in this case.
 
 
 
On Sat, Mar 12, 2016, at 01:24 PM, Gajus Kuizinas wrote:
> I encourage you to make it public and share it with others.
> —
> Reply to this email directly or view it on GitHub[1].
>
 

Links:

  1. https://github.com/gajus/swing/pull/61#issuecomment-195794285

**Pull request closed without merging**
