### PR TITLE
Use specific lodash functions imports to enable tree shaking

### PR DESCRIPTION
**Pull request by qnp**
This allows to reduce final bundle size

### CODE REVIEW

**Comment by gajus** [comment]
Use tree-shaking.

**Comment by qnp** [comment]
Example in a project depending on 'swing', using webpack as a build system and webpack-bundle-analyser plugin:

### Before
Capture d’écran 2019-10-25 à 15 38 01

### After
Capture d’écran 2019-10-25 à 15 37 46

**Comment by qnp** [comment]
Tree shaking was not possible due to current import syntax.

_c.f._ https://www.azavea.com/blog/2019/03/07/lessons-on-tree-shaking-lodash/

> Tree-shaking is syntax-sensitive. To enable tree-shaking in lodash, you have to import functions using syntax like `import foo from 'lodash/foo'`. `import { foo } from 'lodash'` will not tree-shake, nor will, obviously, `import _ from 'lodash'`. Support for this syntax was implemented in Lodash v4.

**Comment by gajus** [comment]
A better solution would be https://github.com/lodash/babel-plugin-lodash.

PRs like this require that _everyone_ is magically aware of this requirement.

**Comment by qnp** [comment]
#141

**Pull request closed without merging**
