### PR TITLE
Fix: change global to window since global does not exists in browsers.

### PR DESCRIPTION
**Pull request by Jule-**
I think you work with some specific builder that understand `global` and probably transpile it for browser but for others please use `window` which seems to be the only available in browsers.

Thanks for your work! ;)

### CODE REVIEW

**Comment by gajus** [comment]
What builder are you using?

**Comment by Jule-** [comment]
I am using aurelia bundler.

**Comment by Jule-** [comment]
Hum, seems that my changes broke one of your tests in your test env...
But on my side:
```
$ mocha --compilers js:babel-register


  DOM
    Stack
      .getCard()
        √ returns card associated with an element
        √ returns null when element is not associated with a card
      .destroyCard()
        √ is called when Card is destroyed
      .getConfig()
        √ returns the config object
        isThrowOut
          √ is invoked in the event of dragend
          √ determines throwOut event
          √ determines throwOut event
        throwOutConfidence
          √ is invoked in the event of dragmove
        rotation
          √ is invoked in the event of dragmove
        transform
          √ is invoked in the event of dragmove (43ms)


  10 passing (425ms)

Done in 2.17s.
```

**Comment by Jule-** [comment]
Hi, any news on this? Thanks.

**Pull request closed without merging**
