### PR TITLE
optimize performance

### PR DESCRIPTION
**Pull request by unbug**
optimize performance with requestAnimationFrame,so now everything works on android device!

### CODE REVIEW

**Comment by gajus** [comment]
@unbug Have you had a chance to test this in the field? If yes, I'd be happy to merge it.

**Comment by unbug** [comment]
I did,and also I build the AMD version [here](https://github.com/unbug/swing-amd),the same codes ;)

**Comment by gajus** [comment]
You are making a lot `cancelMove()` calls that I do not understand because raf will automatically stop when `isDragging` is `false`:

```js
isDraging = true;

(function animation (){
    if (!isDraging) {
        return;
    }

    doMove();

    raf(animation);
}) ();
```

**Comment by gajus** [comment]
https://github.com/gajus/swing/commit/6ec2f061ab94ebcc570cef7a605c7ac8f829bc17

**Comment by unbug** [comment]
@gajus it is a double check

**Comment by rajeevriitm** [comment]
Can I ask whats the need for recursive function? Cant we call the function in each `panmove` event ?

**Pull request closed without merging**
