### PR TITLE
added up/down detection

### PR DESCRIPTION
**Pull request by elmariachi111**
breaks bc for throwout confidence function, though

### CODE REVIEW

**Comment by elmariachi111** [comment]
Completed this one before I noticed https://github.com/gajus/swing/pull/78. This one offers similar features but needs fewer changes. Demonstrating the new directions in the examples, though :)

**Comment by nomanbiniqbal** [comment]
is you are going to publish this change

**Comment by jony89** [comment]
could you please merge this ?

**Comment by gajus** [comment]
https://github.com/gajus/swing/pull/78

**Pull request closed without merging**
