### PR TITLE
Dynamically adding cards to the bottom of stack using an optional prepend argument. Still appending by default

### PR DESCRIPTION
**Pull request by Sparkomatic**
@gajus Hey Gajus, are you ok to merge this please? Let me know your thoughts - thanks.
It was forked from nadangergeo's fork. I don't see any merge issues.

### CODE REVIEW

**Comment by gajus** [comment]
There was a reason why "prepend" was not made as an option. I cannot recall it now. It complicated styling or something like that. Test it out, if it works in your use case scenario, I cannot see a reason for not merging it.

**Comment by Sparkomatic** [comment]
@Gajus OK, cool. A test is failing so I will look at this this evening. Have to go in to a lecture now.

**Comment by Sparkomatic** [comment]
@gajus OK, I just ran the test locally and all tests passed using node 4,5,6 and 7 so I got Travis to run the tests again by closing and then reopening the PR. The prepend is working for my use case and I am  able to add cards to the bottom of the stack now. Good to merge? Thanks, J

**Comment by gajus** [comment]
Thank you

**Comment by nadangergeo** [comment]
Sweet! Didn't catch that the PR went through until now ^^

Thank you for helping out with this @Sparkomatic 👍 I'm guessing we could close my PR? (#93)

**Pull request merged**
